[package]
name = "polymath"
version.workspace = true
description = "public api to crawl selected websites"
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
polymath-queue = { path = "../polymath-queue" }