name: polymath/docker

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
    
env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Publish polymath
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Get tag"
      id: "get-tag"
      shell: "bash"
      run: |
        echo PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: |
            docker build -f docker/Dockerfile -t ghcr.io/lubmminy/polymath:latest .
            docker push ghcr.io/lubmminy/polymath:latest
            docker tag ghcr.io/lubmminy/polymath:latest ghcr.io/gravitalia/remini:${{ steps.get-tag.outputs.PKG_VERSION }}
            docker push ghcr.io/lubmminy/polymath:${{ steps.get-tag.outputs.PKG_VERSION }}
